### PR TITLE
Focus option for sbt-command and sbt:command. If focus is t use pop-t…

### PR DESCRIPTION
**Pull request by tbje**
…o-buffer instead of display-buffer.

### CODE REVIEW

**Comment by tbje** [comment]
Corresponding *ensime-sbt-do-console* for instance:
```
(defun ensime-sbt-do-console ()
  (interactive)
  (sbt-command "console" t))
```

**Comment by hvesalai** [comment]
In #46 @tbje wrote: "I have local changes allowing to pass an optional focus argument to sbt-command and sbt:command. This allows to optionally focus on the buffer by using pop-to-buffer instead of display-buffer. I like it for ensime-sbt-do-run and ensime-sbt-do-console. Would you like me to submit a pull request?"

**Comment by hvesalai** [comment]
It looked useful and didn't break anything so I merged it.

**Comment by hvesalai** [comment]
@tbje Thank you for the commit!

**Comment by tbje** [comment]
Thank you !

**Pull request merged**
