### PR TITLE
Support nested projects

### LINKED ISSUE #16: sbt-start fails to detect nested project
imagine the following project structure

```
root/
  src/
  project/[SBT config]
  sub/
    src/
    project/[SBT config]
```

when `dired` is in the `root/sub` folder, invoking `sbt-start` will start up sbt against `root` and not `sub` as expected.

### PR DESCRIPTION
**Pull request by fommil**
fixes #16 but @hvesalai you weren't sure why we didn't do it this way originally?

### CODE REVIEW

**Comment by hvesalai** [comment]
This was my intention when writing the original implementation. Do you not agree with it?

```
   "Starting from the current default-directory, find the top-most
 parent directory that is an sbt root. An sbt root directory is
 identified by the following rules:
```

**Comment by fommil** [comment]
Yeah, I'm pretty sure we'd want the most inner route otherwise it's impossible to use sbt-mode with nested projects, eg integration test projects for SBT modules.

**Comment by fommil** [comment]
Most inner project (autocorrect hates me)

**Comment by hvesalai** [comment]
Ok, so we need to change it. Maybe have a conf parameter to tell it to work as before. I use a top-level project/Build.scala that contains specs for all projects. Although since the sub-projects don't have any sbt-artefacts, I don't think the change would break it for me.

**Comment by fommil** [comment]
I see. Should be easy to make it optional.

**Comment by fommil** [comment]
@hvesalai  updated

**Pull request merged**
