### PR TITLE
sbt-mode won't compile if hydra is not installed

### PR DESCRIPTION
**Pull request by VlachJosef**
Fix for https://github.com/ensime/emacs-sbt-mode/issues/71

### CODE REVIEW

**Comment by fommil** [comment]
CI failed because `s` wasn't available for emacs 24.3. Weird.

**Comment by VlachJosef** [comment]
I wonder if it can somehow be related to what @hvesalai [said](https://github.com/ensime/emacs-sbt-mode/issues/71#issuecomment-239140949) about `string-suffix-p` function which is emacs 24.4 only.

**Comment by hvesalai** [comment]
Yeah, string-suffix-p is not there for emacs 24.3., so it should be rewritten to use string-match with `$`

**Comment by VlachJosef** [comment]
@fommil I've replaced `string-suffix-p` with `string-match` to support emacs 24.3, but CI build is still failing.

**Comment by fommil** [comment]
@VlachJosef I don't think that was the problem. it looks like `s` just isn't available for emacs 24.3.

I think we're ok to move to 24.5 only, most of melpa has already moved to it.

**Comment by fommil** [comment]
can you please rebase? I pushed a change to the drone build

**Comment by fommil** [comment]
oh, what the hell. we know it works in 24.5. Thanks for fixing!

**Comment by hvesalai** [comment]
@fommil will you update documentation accordingly?

**Pull request merged**
