### PR TITLE
Hydra as interface for sbt

### PR DESCRIPTION
**Pull request by VlachJosef**
This is initial implementation of Hydra for sbt control. It can be run with `sbt-hydra:hydra` command. 
Basic sbt commands are supported: `compile`, `test`, `test:compile`, `clean`, `reload`, `run`. 
There is help available with more details.

### CODE REVIEW

**Comment by fommil** [comment]
I'm very excited about this one, looking forward to trying it out (probably only at home though, I'm using stable releases at work) Thank you so much for sharing!

**Comment by fommil** [comment]
@hvesalai FYI Josef has been showing off various versions of this at the Hack Days in London. It's very very cool. We noticed a few areas that might need improvement for larger projects, but it shouldn't introduce any obvious regressions so definitely worthwhile for the unstable release branch.

**Comment by fommil** [comment]
@VlachJosef could you please add some docs to the website for this under the `sbt-mode` page?

**Comment by VlachJosef** [comment]
@fommil @hvesalai any comments and ideas for improvements are welcome. I'm using this implementation all day long and it covers all my needs.

I will add information into `sbt-mode` section tomorrow.

**Comment by fommil** [comment]
my main thing will be remembering to use it! I have trained by fingers to invoke my `sbt-command` shortcut that it'll take some getting used to. Maybe I should unbind that when I'm at home...

**Comment by VlachJosef** [comment]
Maybe you can invoke `sbt-hydra:hydra` instead of `sbt-command` and see how it will work.

**Comment by fommil** [comment]
@VlachJosef I tried it out on ensime-server and all I get is

```
Please wait! Sbt projects are loading. Sbt Hydra will be ready soon.
```

did I brokened it?

**Comment by hvesalai** [comment]
I'm new to hydra. I checked it out and seems like a nice package. May I ask what kind of key-bindings are you using it for?

Before merging this, please also write the text to be included here: http://ensime.github.io/editors/emacs/sbt-mode/

**Comment by VlachJosef** [comment]
@fommil that message is displayed on the first launch, where sbt is starting and you don't have any projects specified in `dir-locals.el`. It will get projects by running sbt `projects` command. After that you should see a message:
```
Success hydra for projects (api core ensime jerky monkeys s-express server swanky testingDebug testingDocs testingEmpty testingImplicits testingJava testingMacros testingShapeless testingSimple testingSimpleJar testingTiming testutil util) created.
```
Now you just need to run `sbt-hydra:hydra` again to see it. (I guess this is little confusing for new people it would be better to show hydra immediately).

**Comment by fommil** [comment]
@VlachJosef ah but it kept doing that, it failed to parse the project names.

**Comment by VlachJosef** [comment]
@fommil are you testing this on Windows?

**Comment by fommil** [comment]
@VlachJosef nope, that was on my ArchLinux laptop. I'll try again when you're written the docs :smile:

**Comment by VlachJosef** [comment]
@hvesalai there is no key-binding to invoke hydra, it's up to the user to define one. If you mean key-binding hydra itself is defining, you can see it [here](https://github.com/ensime/emacs-sbt-mode/blob/b82553584b6d97d028cb339b0670c76cd042b2d0/sbt-mode-hydra.el#L170-L171)

**Comment by VlachJosef** [comment]
@fommil Can you paste here sbt output you get when running `sbt-hydra:hydra` command? I'm afraid documentation won't help here too much. Are you using custom sbt prompt?

**Comment by VlachJosef** [comment]
@fommil as a workaround you can specify projects in `.dir-locals.el`. For example:
```elisp
((sbt-mode
  (sbt-hydra:projects "api" "core" "ensime" "jerky" "monkeys" "s-express" "server" "swanky" "util")))
```

Then there is no need to parse list of projects when launching sbt.

**Pull request merged**
