### PR TITLE
some ScalaTest warn/error matchers

### PR DESCRIPTION
**Pull request by fommil**
I might have a few more to add as there seem to be many ways for a test to fail.

It would be great if the errors were actually detected by the `error` function, but there is no way to detect what the file is. We might be able to do something smart here in ENSIME... and we can definitely do something when there is a stacktrace.

### CODE REVIEW

**Comment by fommil** [comment]
@hvesalai it would be good if `next-error` didn't try to open a file. What I tend to do is `next-error` followed by a `C-g` to cancel the attempt to open a file. If you can work out a way to suppress that when there is no file, I'd adopt it into my workflow in a heartbeat.

We could try to parse filenames from stacktraces, but I think that's futile because you'd need ENSIME to resolve the stackframes to files on disk.

**Comment by hvesalai** [comment]
Isn't the whole point of next-error to open the location? I don't understand this request.

**Comment by fommil** [comment]
not necessarily. `next-error` also jumps to the error in the output, which is useful when you run a test suite and it might take 20 seconds to find it manually.

**Comment by hvesalai** [comment]
Hmm... ok. I use `next-error` to jump to compile errors.

**Comment by fommil** [comment]
yeah, that still works when sbt outputs compile errors. But if the errors are test errors then the best we can do is jump to the output message of the failure (not the line of source code that failed).

**Comment by hvesalai** [comment]
Yeah. So is it just a regex change then?

**Comment by fommil** [comment]
This PR is just adding a few more things that are considered warnings or errors.

I'll maybe ask on the emacs mailing list if there is a way to customise `next-error` if there isn't any associated source code.

**Comment by hvesalai** [comment]
Doesn't the regexes control where the file is. If the file group is nil, then no file can be opened?

**Comment by fommil** [comment]
hah! You'd think that. If `FILE` is `nil` then it defaults to whatever file was previously found in the same check sequence.

**Comment by fommil** [comment]
emacs `compilation-mode` has got to be **the weirdest** part of emacs.

**Comment by hvesalai** [comment]
You need to specify your own version of function `compilation-next-error-function` (see the documentation for the variable `next-error-function`).

**Comment by fommil** [comment]
uugh, that looks like a massive pain. OK, well I don't see that blocking this PR because it's only if people want to use `next-error` on test failures (which currently `sbt-mode` doesn't support at all). The compile failure `next-error` behaviour is exactly as before.

**Comment by fommil** [comment]
@hvesalai is there anything you'd like me to do before you can merge this? I've been using for a few days and seems quite stable.

**Comment by hvesalai** [comment]
I wanted to still verify your regexes, but didn't have time.

**Comment by fommil** [comment]
Cool. BTW, I'd actually been using these regexes in my https://github.com/fommil/maker-mode/blob/master/maker-mode.el#L178 (I was working on a project with an in-house build tool. Yeah, just awesome).

In my maker mode I had `^\\.*` at the beginning of the regexes because `maker` sometimes didn't do a newline before printing out the compiler messages. I think `sbt` is more reliable at this, so I left them out since they are relatively expensive.

**Comment by fommil** [comment]
hmm, I'm just noticing that if `setq-local` takes a list (like `setq`) maybe it should just all be in one block for cleanliness sake.

**Comment by hvesalai** [comment]
Ok, added some comments to the regexes. They are missing support for Windows file names.

**Comment by fommil** [comment]
Good spot. Yeah, I wish somebody would write a new regexp layer for emacs... it sucks that it doesn't support modern conventions.

**Comment by fommil** [comment]
I've got an upcoming change which does this sort of thing

```
"""\w:?[^:\s]+"""
```

I'd have done a non-capturing group for `\w:` but I don't think emacs supports it.

**Comment by fommil** [comment]
ok, that broke it. I'll send another fix later. Don't merge yet.

**Comment by fommil** [comment]
ok, that should be working now.

**Comment by fommil** [comment]
Is it working for you on Windows?

**Comment by fommil** [comment]
ping

**Comment by hvesalai** [comment]
@fommil did you notice my comment above?

**Comment by fommil** [comment]
@hvesalai the one about supporting spaces? Yeah, I don't think this was ever supported. It would be quite tricky to support it actually, but I can add it if you like.

BTW, I spoke to Bill Venners at Scaladays last month (he's the Scalatest author) about getting Scalatest to perhaps output more information for failed tests. He said that everything is already available in the programmatic API but I've been suggesting that the runner should include everything in emacs-friendly terms (see the reference above). It might be worth picking up that conversation at some point.

**Comment by fommil** [comment]
I forgot to test this on Windows. I will do so.

**Pull request closed without merging**
