### PR TITLE
Save sbt commands history into a file

### PR DESCRIPTION
**Pull request by VlachJosef**
Save sbt commands history into a file and read it back next time sbt is launched.

### CODE REVIEW

**Comment by fommil** [comment]
This would be good for the shell input too!

**Comment by fommil** [comment]
I should really start using sbt hydra now that I've been back on GNU/Linux for ages.

**Comment by VlachJosef** [comment]
Definitely, give it a try and let me know your thoughts.

**Comment by fommil** [comment]
yup, this is cool!

**Pull request merged**
